use brain_core::errors::BrainError;
use brain_core::repositories::RepositorySet;
use brain_domain::{Edge, NodeId};
use std::collections::{HashSet, VecDeque};
use std::time::Instant;

/// Budget boundaries for graph traversal operations to prevent resource exhaustion.
#[derive(Debug, Clone)]
pub struct TraversalBudget {
    /// Maximum search depth from source node(s).
    pub max_depth: usize,
    /// Maximum unique nodes to traverse/collect.
    pub max_nodes: usize,
    /// Maximum edges to traverse.
    pub max_edges: usize,
    /// Whether to prevent cycles/revisiting nodes during traversal.
    pub prevent_cycles: bool,
    /// Soft execution deadline.
    pub deadline: Option<Instant>,
    /// Whether to strictly respect directed edge constraints.
    pub respect_directionality: bool,
}

impl Default for TraversalBudget {
    fn default() -> Self {
        Self {
            max_depth: 1,
            max_nodes: 50,
            max_edges: 100,
            prevent_cycles: true,
            deadline: None,
            respect_directionality: false,
        }
    }
}

/// Service handling bounded graph traversal operations.
///
/// Invariants:
/// - Purely read-only interface; performs no writes or repository mutations.
pub struct Graph;

impl Graph {
    /// Bounded Breadth-First Search (BFS) neighborhood expansion from a set of starting nodes.
    pub fn expand_neighbors(
        &self,
        repos: &dyn RepositorySet,
        registry: &brain_domain::RelationRegistry,
        start_nodes: &[NodeId],
        budget: &TraversalBudget,
    ) -> Result<Vec<Edge>, BrainError> {
        let mut visited = HashSet::new();
        let mut traversed_edges = HashSet::new();
        let mut result_edges = Vec::new();
        let mut queue = VecDeque::new();

        for &id in start_nodes {
            queue.push_back((id, 0));
            visited.insert(id);
        }

        while let Some((current_id, depth)) = queue.pop_front() {
            // Check deadline
            if let Some(deadline) = budget.deadline {
                if Instant::now() > deadline {
                    break;
                }
            }

            // Depth limit
            if depth >= budget.max_depth {
                continue;
            }

            // Node count limit
            if visited.len() > budget.max_nodes {
                break;
            }

            // Get connections for current node
            let connections = repos.edges().get_connections(&current_id)?;
            for edge in connections {
                // Edge count limit
                if result_edges.len() >= budget.max_edges {
                    break;
                }

                // Check cycle prevention
                let is_forward = edge.source == current_id;
                if budget.respect_directionality {
                    let policy = registry.traversal_policy(edge.relation.id());
                    if !policy.can_traverse(is_forward) {
                        continue;
                    }
                }

                let next_node = if is_forward {
                    edge.target
                } else {
                    edge.source
                };

                let edge_key = (edge.source, edge.target, edge.relation.to_string());
                if traversed_edges.contains(&edge_key) {
                    continue;
                }
                traversed_edges.insert(edge_key);
                result_edges.push(edge.clone());

                if !visited.contains(&next_node)
                    && (!budget.prevent_cycles || visited.insert(next_node))
                {
                    queue.push_back((next_node, depth + 1));
                }
            }
        }

        Ok(result_edges)
    }
}

/// Consolidated analysis report generated by read-only graph metrics evaluation.
#[derive(Debug, Clone)]
pub struct AnalysisReport {
    /// Mapping of node IDs to updated confidence/importance scores.
    pub confidence_scores: std::collections::HashMap<String, f32>,
    /// Mapping of edge/node IDs to decay values.
    pub decay_scores: std::collections::HashMap<String, f32>,
}

/// Read-only trait for computing structural facts about the graph.
///
/// Invariants:
/// - Purely read-only; performs no writes or repository mutations.
pub trait GraphAnalyzer: Send + Sync {
    /// Computes analysis report on the current graph state.
    fn compute_analysis(&self, repos: &dyn RepositorySet) -> Result<AnalysisReport, BrainError>;
}

/// Service that applies computed analysis mutations back to the repository.
///
/// Invariants:
/// - Never computes analysis independently (takes an existing report as input).
pub trait GraphMaintenanceService: Send + Sync {
    /// Applies the computed analysis report back to persistence.
    fn apply_analysis(&self, repos: &dyn RepositorySet, report: AnalysisReport) -> Result<(), BrainError>;
}

/// Placeholder implementation of GraphAnalyzer for Phase 2.
pub struct PlaceholderGraphAnalyzer;

impl GraphAnalyzer for PlaceholderGraphAnalyzer {
    fn compute_analysis(&self, _repos: &dyn RepositorySet) -> Result<AnalysisReport, BrainError> {
        Ok(AnalysisReport {
            confidence_scores: std::collections::HashMap::new(),
            decay_scores: std::collections::HashMap::new(),
        })
    }
}

/// Placeholder implementation of GraphMaintenanceService for Phase 2.
pub struct PlaceholderGraphMaintenanceService;

impl GraphMaintenanceService for PlaceholderGraphMaintenanceService {
    fn apply_analysis(&self, _repos: &dyn RepositorySet, _report: AnalysisReport) -> Result<(), BrainError> {
        Ok(())
    }
}
