use serde::{Deserialize, Serialize};

/// Data Transfer Object representing a node, decoupling storage/internal representations from API/UI.
#[non_exhaustive]
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct NodeDTO {
    /// Stringified unique node identifier (standardized UUID).
    pub id: String,
    /// Name or label of the node.
    pub label: String,
    /// Category or type classification.
    pub node_type: String,
    /// Additional JSON-value properties.
    pub attributes: serde_json::Value,
}

impl NodeDTO {
    /// Creates a new `NodeDTO`.
    pub fn new(
        id: String,
        label: String,
        node_type: String,
        attributes: serde_json::Value,
    ) -> Self {
        Self {
            id,
            label,
            node_type,
            attributes,
        }
    }
}

/// Data Transfer Object representing a relationship edge between two nodes.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EdgeDTO {
    /// Stringified identifier of the source node.
    pub source: String,
    /// Stringified identifier of the target node.
    pub target: String,
    /// Relation label (e.g. "authored").
    pub relation: String,
    /// Relative weight/confidence score.
    pub weight: f64,
}

impl EdgeDTO {
    /// Creates a new `EdgeDTO`.
    pub fn new(source: String, target: String, relation: String, weight: f64) -> Self {
        Self {
            source,
            target,
            relation,
            weight,
        }
    }
}

/// Data Transfer Object representing a high-dimensional node embedding.
#[non_exhaustive]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbeddingDTO {
    /// Stringified identifier of the associated node.
    pub node_id: String,
    /// Floating-point vector values.
    pub vector: Vec<f32>,
}

impl EmbeddingDTO {
    /// Creates a new `EmbeddingDTO`.
    pub fn new(node_id: String, vector: Vec<f32>) -> Self {
        Self { node_id, vector }
    }
}

/// Data Transfer Object encapsulating a memory unit including a node and its local edge connections.
#[non_exhaustive]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryDTO {
    /// The target node metadata DTO.
    pub node: NodeDTO,
    /// Directed incoming edges to this node.
    pub incoming_edges: Vec<EdgeDTO>,
    /// Directed outgoing edges from this node.
    pub outgoing_edges: Vec<EdgeDTO>,
}

impl MemoryDTO {
    /// Creates a new `MemoryDTO`.
    pub fn new(node: NodeDTO, incoming_edges: Vec<EdgeDTO>, outgoing_edges: Vec<EdgeDTO>) -> Self {
        Self {
            node,
            incoming_edges,
            outgoing_edges,
        }
    }
}

/// Data Transfer Object representing a structured reconciliation diagnostic item.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PassDiagnosticDTO {
    /// Diagnostic severity level string ("info", "warning", "error").
    pub severity: String,
    /// Machine-readable diagnostic code.
    pub code: String,
    /// Human-readable diagnostic message.
    pub message: String,
    /// Stringified entity identifier, if associated.
    pub entity_id: Option<String>,
}

/// Data Transfer Object representing a merge proposal generated during reconciliation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct MergeProposalDTO {
    /// Stringified candidate source entity identifier.
    pub source_entity_id: String,
    /// Stringified canonical target entity identifier.
    pub target_entity_id: String,
    /// Match confidence score.
    pub confidence: f32,
    /// Rationale explaining the proposal.
    pub rationale: String,
    /// Detailed feature similarity scores.
    pub feature_scores: std::collections::HashMap<String, f32>,
}

/// Data Transfer Object representing a contradiction record.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ContradictionRecordDTO {
    /// Contradiction classification kind ("logical", "temporal").
    pub kind: String,
    /// Stringified first conflicting entity ID.
    pub entity_a: String,
    /// Stringified second conflicting entity ID.
    pub entity_b: String,
    /// Confidence score.
    pub confidence: f32,
    /// Detailed explanation of the contradiction.
    pub rationale: String,
}

/// Data Transfer Object representing a full pass execution report.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PassReportDTO {
    /// Name of the reconciliation pass.
    pub pass_name: String,
    /// Number of items inspected.
    pub items_processed: usize,
    /// Number of changes applied.
    pub changes_applied: usize,
    /// Diagnostics generated by the pass.
    pub diagnostics: Vec<PassDiagnosticDTO>,
    /// Merge proposals generated by the pass.
    pub merge_proposals: Vec<MergeProposalDTO>,
    /// Contradictions detected by the pass.
    pub contradiction_records: Vec<ContradictionRecordDTO>,
    /// Pass execution duration in milliseconds.
    pub duration_ms: u64,
}

/// Data Transfer Object representing execution metrics of a reflection task.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TaskReportDTO {
    /// Name of the reflection task.
    pub task_name: String,
    /// Task classification kind string.
    pub task_kind: String,
    /// Number of items inspected.
    pub items_processed: usize,
    /// Number of changes applied.
    pub changes_applied: usize,
    /// Diagnostics generated by the task.
    pub diagnostics: Vec<PassDiagnosticDTO>,
    /// Task duration in milliseconds.
    pub duration_ms: u64,
}

/// Data Transfer Object representing full reflection run metrics.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ReflectionReportDTO {
    /// Reflection execution mode string ("startup", "periodic", "idle", "manual", "dream").
    pub execution_mode: String,
    /// Task reports generated in execution plan sequence.
    pub task_reports: Vec<TaskReportDTO>,
    /// Cumulative duration in milliseconds.
    pub total_duration_ms: u64,
    /// Cumulative changes applied.
    pub total_changes: usize,
}
