use crate::entities::{Edge, KnowledgeGraph};
use crate::identifiers::{EdgeId, NodeId, RelationId};
use crate::relations::RelationRegistry;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};

/// Typed targets affected by validation diagnostics.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(tag = "type", content = "id", rename_all = "lowercase")]
pub enum AffectedElement {
    /// A specific Node ID.
    Node(NodeId),
    /// A specific Edge ID.
    Edge(EdgeId),
    /// A specific Relation ID.
    Relation(RelationId),
}

/// Severity classification of diagnostics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DiagnosticSeverity {
    /// Actionable hard errors that block production or ingestion.
    Error,
    /// Warnings that signal structural anomalies but do not halt operations.
    Warning,
}

/// Category classification of diagnostics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DiagnosticCategory {
    /// Missing target/source nodes referential checks.
    ReferentialIntegrity,
    /// Provenance metadata checks.
    Provenance,
    /// Missing derivation metadata on inferred edges.
    ExplanationCompleteness,
    /// Unregistered relation kinds check.
    RegistryConformance,
    /// Redundant duplicate edge checks.
    EdgeUniqueness,
    /// Circular reasoning/graph cycle checks.
    ExplanationAcyclicity,
}

/// A structured validation diagnostic report.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct ValidationDiagnostic {
    /// Stable machine-readable diagnostic error/warning code.
    pub code: String,
    /// Severity of the diagnostic.
    pub severity: DiagnosticSeverity,
    /// Category/type of checking breached.
    pub category: DiagnosticCategory,
    /// Human-readable explanation.
    pub message: String,
    /// Identifiers of the affected graph elements.
    pub affected: Vec<AffectedElement>,
}

/// Immutable validation context providing pre-computed indices.
pub struct ValidationContext<'a> {
    /// Reference to the underlying knowledge graph.
    pub graph: &'a KnowledgeGraph,
    /// Reference to the relation schema registry.
    pub registry: &'a RelationRegistry,
    /// Mapping of target node to source nodes and edges connected to it (precomputed).
    pub incoming: HashMap<NodeId, Vec<&'a Edge>>,
}

impl<'a> ValidationContext<'a> {
    /// Creates a new `ValidationContext` indexing incoming edges.
    pub fn new(graph: &'a KnowledgeGraph, registry: &'a RelationRegistry) -> Self {
        let mut incoming: HashMap<NodeId, Vec<&'a Edge>> = HashMap::new();
        for edge in graph.edges.values() {
            incoming.entry(edge.target).or_default().push(edge);
        }
        Self {
            graph,
            registry,
            incoming,
        }
    }
}

/// Performance and inspection metrics for a validation pass.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PassMetric {
    /// Unique identifier of the pass.
    pub pass_id: String,
    /// Duration of the pass execution in milliseconds.
    pub duration_ms: f64,
    /// Count of elements inspected during the pass.
    pub elements_inspected: usize,
    /// Number of diagnostics generated by this pass.
    pub diagnostic_count: usize,
}

/// Overall health and validation status summary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidationReportSummary {
    /// Total count of errors reported.
    pub total_errors: usize,
    /// Total count of warnings reported.
    pub total_warnings: usize,
    /// True if no error-level diagnostics are present in the report.
    pub is_valid: bool,
}

/// An immutable snapshot report of the knowledge graph validation state.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidationReport {
    /// List of validation diagnostics generated.
    pub diagnostics: Vec<ValidationDiagnostic>,
    /// Summary of validation status and counts.
    pub summary: ValidationReportSummary,
    /// Pass metrics including execution duration and elements inspected.
    pub metrics: Vec<PassMetric>,
}

/// Represents a distinct validation pass over the graph context.
pub trait ValidationPass {
    /// Unique stable identifier of the validation pass.
    fn id(&self) -> &'static str;

    /// Stable descriptive overview of the pass scope.
    fn description(&self) -> &'static str;

    /// Runs validation logic against the context, reporting diagnostic breaches.
    /// Returns the number of elements inspected.
    fn run(&self, ctx: &ValidationContext, diagnostics: &mut Vec<ValidationDiagnostic>) -> usize;
}

/// Orchestrates execution of registered validation passes over the knowledge graph.
pub struct GraphValidator;

impl GraphValidator {
    /// Runs all standard validation passes over the graph and registry, returning a complete ValidationReport.
    pub fn validate(graph: &KnowledgeGraph, registry: &RelationRegistry) -> ValidationReport {
        let ctx = ValidationContext::new(graph, registry);
        let mut diagnostics = Vec::new();
        let mut metrics = Vec::new();

        let passes: &[&dyn ValidationPass] = &[
            &IdentityValidationPass,
            &RegistryValidationPass,
            &StructuralValidationPass,
            &ExplanationValidationPass,
        ];

        for pass in passes {
            let start = std::time::Instant::now();
            let prev_len = diagnostics.len();
            let elements_inspected = pass.run(&ctx, &mut diagnostics);
            let duration = start.elapsed();

            metrics.push(PassMetric {
                pass_id: pass.id().to_string(),
                duration_ms: duration.as_secs_f64() * 1000.0,
                elements_inspected,
                diagnostic_count: diagnostics.len() - prev_len,
            });
        }

        // Sort diagnostics stably (ValidationDiagnostic derives Ord)
        diagnostics.sort();

        let total_errors = diagnostics
            .iter()
            .filter(|d| d.severity == DiagnosticSeverity::Error)
            .count();
        let total_warnings = diagnostics
            .iter()
            .filter(|d| d.severity == DiagnosticSeverity::Warning)
            .count();

        ValidationReport {
            diagnostics,
            summary: ValidationReportSummary {
                total_errors,
                total_warnings,
                is_valid: total_errors == 0,
            },
            metrics,
        }
    }
}

/// Pass 1: IdentityValidationPass
/// Validates referential integrity: every edge's source and target nodes must exist.
pub struct IdentityValidationPass;

impl ValidationPass for IdentityValidationPass {
    fn id(&self) -> &'static str {
        "identity"
    }

    fn description(&self) -> &'static str {
        "Checks referential integrity by validating that all edge source and target nodes exist in the graph"
    }

    fn run(&self, ctx: &ValidationContext, diagnostics: &mut Vec<ValidationDiagnostic>) -> usize {
        for (edge_id, edge) in &ctx.graph.edges {
            if !ctx.graph.nodes.contains_key(&edge.source) {
                diagnostics.push(ValidationDiagnostic {
                    code: "VAL-001".to_string(),
                    severity: DiagnosticSeverity::Error,
                    category: DiagnosticCategory::ReferentialIntegrity,
                    message: format!("Source node '{}' does not exist in the graph", edge.source),
                    affected: vec![
                        AffectedElement::Edge(edge_id.clone()),
                        AffectedElement::Node(edge.source),
                    ],
                });
            }
            if !ctx.graph.nodes.contains_key(&edge.target) {
                diagnostics.push(ValidationDiagnostic {
                    code: "VAL-002".to_string(),
                    severity: DiagnosticSeverity::Error,
                    category: DiagnosticCategory::ReferentialIntegrity,
                    message: format!("Target node '{}' does not exist in the graph", edge.target),
                    affected: vec![
                        AffectedElement::Edge(edge_id.clone()),
                        AffectedElement::Node(edge.target),
                    ],
                });
            }
        }
        ctx.graph.edges.len()
    }
}

/// Pass 2: RegistryValidationPass
/// Validates registry conformance: every edge's relation kind must be defined in the RelationRegistry.
pub struct RegistryValidationPass;

impl ValidationPass for RegistryValidationPass {
    fn id(&self) -> &'static str {
        "registry"
    }

    fn description(&self) -> &'static str {
        "Validates that all edge relations are registered in the RelationRegistry schema definitions"
    }

    fn run(&self, ctx: &ValidationContext, diagnostics: &mut Vec<ValidationDiagnostic>) -> usize {
        for (edge_id, edge) in &ctx.graph.edges {
            if ctx.registry.get_kind(edge.relation).is_none() {
                diagnostics.push(ValidationDiagnostic {
                    code: "VAL-003".to_string(),
                    severity: DiagnosticSeverity::Error,
                    category: DiagnosticCategory::RegistryConformance,
                    message: format!("Relation kind '{}' is not registered", edge.relation),
                    affected: vec![
                        AffectedElement::Edge(edge_id.clone()),
                        AffectedElement::Relation(edge_id.relation.clone()),
                    ],
                });
            }
        }
        ctx.graph.edges.len()
    }
}

/// Pass 3: StructuralValidationPass
/// Validates edge uniqueness (no redundant edges of same (source, target, relation)) and detects invalid loops.
pub struct StructuralValidationPass;

impl ValidationPass for StructuralValidationPass {
    fn id(&self) -> &'static str {
        "structural"
    }

    fn description(&self) -> &'static str {
        "Checks structural graph patterns like edge uniqueness and self-loop suppression"
    }

    fn run(&self, ctx: &ValidationContext, diagnostics: &mut Vec<ValidationDiagnostic>) -> usize {
        let mut seen = HashSet::new();
        for (edge_id, edge) in &ctx.graph.edges {
            // Edge uniqueness check
            let key = (edge.source, edge.target, edge.relation.id());
            if !seen.insert(key) {
                diagnostics.push(ValidationDiagnostic {
                    code: "VAL-004".to_string(),
                    severity: DiagnosticSeverity::Error,
                    category: DiagnosticCategory::EdgeUniqueness,
                    message: format!(
                        "Redundant edge definition found between '{}' and '{}' for relation '{}'",
                        edge.source, edge.target, edge.relation
                    ),
                    affected: vec![AffectedElement::Edge(edge_id.clone())],
                });
            }

            // Self-loop check (inferred or extracted edges should not connect a node to itself)
            if edge.source == edge.target {
                diagnostics.push(ValidationDiagnostic {
                    code: "VAL-005".to_string(),
                    severity: DiagnosticSeverity::Error,
                    category: DiagnosticCategory::ReferentialIntegrity,
                    message: format!("Invalid self-loop edge found on node '{}'", edge.source),
                    affected: vec![
                        AffectedElement::Edge(edge_id.clone()),
                        AffectedElement::Node(edge.source),
                    ],
                });
            }
        }
        ctx.graph.edges.len()
    }
}

/// Pass 4: ExplanationValidationPass
/// Validates explanation completeness and derivation acyclicity.
pub struct ExplanationValidationPass;

impl ValidationPass for ExplanationValidationPass {
    fn id(&self) -> &'static str {
        "explanation"
    }

    fn description(&self) -> &'static str {
        "Verifies that all inferred edges carry complete derivation records, referenced supporting edges exist, and reasoning chains are acyclic"
    }

    fn run(&self, ctx: &ValidationContext, diagnostics: &mut Vec<ValidationDiagnostic>) -> usize {
        for (edge_id, edge) in &ctx.graph.edges {
            if edge.provenance.source == crate::entities::ProvenanceSource::Inferred {
                let Some(ref derivation) = edge.derivation else {
                    diagnostics.push(ValidationDiagnostic {
                        code: "VAL-006".to_string(),
                        severity: DiagnosticSeverity::Error,
                        category: DiagnosticCategory::ExplanationCompleteness,
                        message: format!(
                            "Inferred edge '{}' is missing a derivation record",
                            edge_id
                        ),
                        affected: vec![AffectedElement::Edge(edge_id.clone())],
                    });
                    continue;
                };

                // Check explanation completeness (supporting edges must exist)
                for sup_id in &derivation.supporting_edges {
                    if !ctx.graph.edges.contains_key(sup_id) {
                        diagnostics.push(ValidationDiagnostic {
                            code: "VAL-007".to_string(),
                            severity: DiagnosticSeverity::Error,
                            category: DiagnosticCategory::ExplanationCompleteness,
                            message: format!(
                                "Inferred edge '{}' references non-existent supporting edge '{}'",
                                edge_id, sup_id
                            ),
                            affected: vec![
                                AffectedElement::Edge(edge_id.clone()),
                                AffectedElement::Edge(sup_id.clone()),
                            ],
                        });
                    }
                }
            } else {
                // Non-inferred edges must NOT have derivation records (enforces immutable boundaries)
                if edge.derivation.is_some() {
                    diagnostics.push(ValidationDiagnostic {
                        code: "VAL-008".to_string(),
                        severity: DiagnosticSeverity::Error,
                        category: DiagnosticCategory::ExplanationCompleteness,
                        message: format!(
                            "Source edge '{}' (provenance: {:?}) cannot contain derivation records",
                            edge_id, edge.provenance.source
                        ),
                        affected: vec![AffectedElement::Edge(edge_id.clone())],
                    });
                }
            }
        }

        // Circular Reasoning / Explanation Acyclicity Check
        // We traverse the derivation graph as a directed dependency graph.
        // For each derived/inferred edge, we walk its derivation supporting_edges.
        let mut visited = HashSet::new();
        let mut stack = HashSet::new();

        for edge_id in ctx.graph.edges.keys() {
            let mut path = Vec::new();
            check_cycles(
                edge_id,
                ctx,
                &mut visited,
                &mut stack,
                &mut path,
                diagnostics,
            );
        }
        ctx.graph.edges.len()
    }
}

fn check_cycles(
    edge_id: &EdgeId,
    ctx: &ValidationContext,
    visited: &mut HashSet<EdgeId>,
    stack: &mut HashSet<EdgeId>,
    path: &mut Vec<EdgeId>,
    diagnostics: &mut Vec<ValidationDiagnostic>,
) {
    if stack.contains(edge_id) {
        // Cycle detected!
        let cycle_start_index = path.iter().position(|id| id == edge_id).unwrap_or(0);
        let mut cycle_path = path[cycle_start_index..].to_vec();
        cycle_path.push(edge_id.clone());

        let cycle_str = cycle_path
            .iter()
            .map(|id| id.to_string())
            .collect::<Vec<String>>()
            .join(" -> ");

        diagnostics.push(ValidationDiagnostic {
            code: "VAL-009".to_string(),
            severity: DiagnosticSeverity::Error,
            category: DiagnosticCategory::ExplanationAcyclicity,
            message: format!(
                "Circular reasoning cycle detected in derivation chain: {}",
                cycle_str
            ),
            affected: cycle_path.into_iter().map(AffectedElement::Edge).collect(),
        });
        return;
    }

    if visited.contains(edge_id) {
        return;
    }

    visited.insert(edge_id.clone());
    stack.insert(edge_id.clone());
    path.push(edge_id.clone());

    if let Some(edge) = ctx.graph.edges.get(edge_id) {
        if let Some(ref derivation) = edge.derivation {
            for sup_id in &derivation.supporting_edges {
                check_cycles(sup_id, ctx, visited, stack, path, diagnostics);
            }
        }
    }

    path.pop();
    stack.remove(edge_id);
}
