//! Job execution strategies, contexts, and registry mapping.

use async_trait::async_trait;
use brain_domain::{Artifact, JobId, JobKind, JobTimestamp};
use parking_lot::Mutex;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tokio_util::sync::CancellationToken;

/// Strongly-typed error payload indicating job execution failure.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct JobExecutionFailure(pub String);

/// Value object containing the result outputs generated by job execution.
#[derive(Debug, Clone)]
pub struct JobExecutionResult {
    /// List of produced output artifacts.
    pub artifacts: Vec<Artifact>,
    /// Chronological list of trace log messages.
    pub logs: Vec<(JobTimestamp, String)>,
}

/// Shared trace logging context for active worker execution.
#[derive(Debug, Clone)]
pub struct JobExecutionContext {
    /// Cancellation token that workers poll to cooperatively abort.
    pub cancellation_token: CancellationToken,
    /// Thread-safe in-memory log buffer.
    pub logs: Arc<Mutex<Vec<(JobTimestamp, String)>>>,
}

impl JobExecutionContext {
    /// Creates a new `JobExecutionContext` instance.
    pub fn new(cancellation_token: CancellationToken) -> Self {
        Self {
            cancellation_token,
            logs: Arc::new(Mutex::new(Vec::new())),
        }
    }

    /// Append a trace log line to the context buffer.
    pub fn log(&self, message: String) {
        let timestamp = JobTimestamp(
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs(),
        );
        self.logs.lock().push((timestamp, message));
    }
}

/// Execution strategy interface matching background task kinds.
#[async_trait]
pub trait JobExecutor: Send + Sync {
    /// Execute the business logic of the job.
    async fn execute(
        &self,
        id: JobId,
        ctx: &JobExecutionContext,
    ) -> Result<JobExecutionResult, JobExecutionFailure>;
}

/// Thread-safe registry mapping JobKind classifications to executors.
#[derive(Clone, Default)]
pub struct JobExecutorRegistry {
    executors: Arc<HashMap<JobKind, Arc<dyn JobExecutor>>>,
}

impl JobExecutorRegistry {
    /// Creates an empty registry.
    pub fn new() -> Self {
        Self {
            executors: Arc::new(HashMap::new()),
        }
    }

    /// Register a new executor for a given JobKind.
    pub fn register(&mut self, kind: JobKind, executor: Arc<dyn JobExecutor>) {
        let mut map = (*self.executors).clone();
        map.insert(kind, executor);
        self.executors = Arc::new(map);
    }

    /// Retrieve the executor mapped to a given JobKind.
    pub fn get(&self, kind: JobKind) -> Option<Arc<dyn JobExecutor>> {
        self.executors.get(&kind).cloned()
    }
}
