//! Concrete reconciliation compiler passes, diagnostic reports, and pipeline coordinator.

use brain_domain::{
    CanonicalEntity, ContradictionKind, EntityId, KnowledgeState, Normalizer, SourceId,
};
use std::collections::HashMap;
use std::time::{Duration, Instant};

/// Severity level for pass diagnostics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum DiagnosticSeverity {
    /// Informational note.
    Info,
    /// Non-fatal warning.
    Warning,
    /// Severe diagnostic error.
    Error,
}

/// Structured diagnostic item produced during compiler pass execution.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PassDiagnostic {
    /// Diagnostic severity level.
    pub severity: DiagnosticSeverity,
    /// Machine-readable error or warning code.
    pub code: String,
    /// Human-readable diagnostic message.
    pub message: String,
    /// Associated target entity identifier, if applicable.
    pub entity_id: Option<EntityId>,
}

/// Structured merge proposal generated by duplicate detection without destructive inline mutation.
#[derive(Debug, Clone, PartialEq)]
pub struct MergeProposal {
    /// Identifier of the candidate entity to merge from.
    pub source_entity_id: EntityId,
    /// Identifier of the target canonical entity to merge into.
    pub target_entity_id: EntityId,
    /// Match confidence score (0.0 to 1.0).
    pub confidence: f32,
    /// Individual feature similarity scores (e.g., lexical, alias, attribute).
    pub feature_scores: HashMap<String, f32>,
    /// Rationale explaining why the merge is proposed.
    pub rationale: String,
    /// Supporting observation source IDs.
    pub supporting_observations: Vec<SourceId>,
}

/// Detailed contradiction record capturing opposing entity or fact claims.
#[derive(Debug, Clone, PartialEq)]
pub struct ContradictionRecord {
    /// Classification kind (Logical vs. Temporal).
    pub kind: ContradictionKind,
    /// First conflicting entity.
    pub entity_a: EntityId,
    /// Second conflicting entity.
    pub entity_b: EntityId,
    /// Confidence score of the contradiction assessment.
    pub confidence: f32,
    /// Detailed explanation of the contradiction.
    pub rationale: String,
    /// Absolute timestamp delta between contradictory claims.
    pub timestamp_delta: u64,
}

/// Execution metrics and diagnostic report returned by a reconciliation pass.
#[derive(Debug, Clone, PartialEq)]
pub struct PassReport {
    /// Name of the executed reconciliation pass.
    pub pass_name: &'static str,
    /// Number of items inspected during execution.
    pub items_processed: usize,
    /// Number of state or structural mutations applied.
    pub changes_applied: usize,
    /// Structured diagnostic messages generated.
    pub diagnostics: Vec<PassDiagnostic>,
    /// Merge proposals generated by the pass, if any.
    pub merge_proposals: Vec<MergeProposal>,
    /// Contradictions detected by the pass, if any.
    pub contradiction_records: Vec<ContradictionRecord>,
    /// Execution duration.
    pub duration: Duration,
}

impl PassReport {
    /// Helper constructor for basic pass reports without proposals/contradictions.
    pub fn basic(
        pass_name: &'static str,
        items_processed: usize,
        changes_applied: usize,
        diagnostics: Vec<PassDiagnostic>,
        duration: Duration,
    ) -> Self {
        Self {
            pass_name,
            items_processed,
            changes_applied,
            diagnostics,
            merge_proposals: Vec::new(),
            contradiction_records: Vec::new(),
            duration,
        }
    }
}

/// Contract for deterministic, idempotent, and composable graph reconciliation passes.
pub trait ReconciliationPass: Send + Sync {
    /// Returns the static name of the reconciliation pass.
    fn name(&self) -> &'static str;

    /// Executes the pass deterministically on a slice of canonical entities.
    fn execute(&self, entities: &mut Vec<CanonicalEntity>) -> PassReport;
}

/// Conservative lexical normalization pass.
/// Trims whitespace and normalizes case on names and aliases without mutating `EntityId`s.
#[derive(Debug, Clone, Default)]
pub struct EntityNormalizationPass;

impl EntityNormalizationPass {
    /// Creates a new `EntityNormalizationPass`.
    pub fn new() -> Self {
        Self
    }
}

impl ReconciliationPass for EntityNormalizationPass {
    fn name(&self) -> &'static str {
        "EntityNormalizationPass"
    }

    fn execute(&self, entities: &mut Vec<CanonicalEntity>) -> PassReport {
        let start = Instant::now();
        let mut changes_applied = 0;
        let items_processed = entities.len();
        let mut diagnostics = Vec::new();

        for entity in entities.iter_mut() {
            let normalized_name = Normalizer::normalize(&entity.preferred_name);
            if normalized_name != entity.preferred_name {
                entity.preferred_name = normalized_name;
                changes_applied += 1;
            }

            let mut normalized_aliases = Vec::with_capacity(entity.aliases.len());
            let mut alias_changed = false;

            for alias in &entity.aliases {
                let norm_alias = Normalizer::normalize(alias);
                if norm_alias != *alias {
                    alias_changed = true;
                }
                if !norm_alias.is_empty() && !normalized_aliases.contains(&norm_alias) {
                    normalized_aliases.push(norm_alias);
                }
            }

            if alias_changed || normalized_aliases.len() != entity.aliases.len() {
                entity.aliases = normalized_aliases;
                changes_applied += 1;
            }

            if entity.preferred_name.is_empty() {
                diagnostics.push(PassDiagnostic {
                    severity: DiagnosticSeverity::Warning,
                    code: "EMPTY_PREFERRED_NAME".to_string(),
                    message: format!(
                        "Entity {} has empty preferred_name after normalization",
                        entity.id
                    ),
                    entity_id: Some(entity.id),
                });
            }
        }

        PassReport::basic(
            self.name(),
            items_processed,
            changes_applied,
            diagnostics,
            start.elapsed(),
        )
    }
}

/// Idempotent alias resolution pass.
/// Builds alias lookup tables and resolves mapped aliases to canonical `EntityId`s without identity mutation.
#[derive(Debug, Clone, Default)]
pub struct AliasResolutionPass {
    alias_map: HashMap<String, EntityId>,
}

impl AliasResolutionPass {
    /// Creates a new `AliasResolutionPass` with optional pre-defined alias mappings.
    pub fn new(alias_map: HashMap<String, EntityId>) -> Self {
        Self { alias_map }
    }
}

impl ReconciliationPass for AliasResolutionPass {
    fn name(&self) -> &'static str {
        "AliasResolutionPass"
    }

    fn execute(&self, entities: &mut Vec<CanonicalEntity>) -> PassReport {
        let start = Instant::now();
        let mut changes_applied = 0;
        let items_processed = entities.len();
        let mut diagnostics = Vec::new();

        let mut active_lookup = self.alias_map.clone();
        for entity in entities.iter() {
            for alias in &entity.aliases {
                active_lookup.entry(alias.clone()).or_insert(entity.id);
            }
        }

        for entity in entities.iter_mut() {
            let normalized_name = Normalizer::normalize(&entity.preferred_name);
            if let Some(&canonical_id) = active_lookup.get(&normalized_name) {
                if canonical_id != entity.id && !entity.merge_history.contains(&canonical_id) {
                    diagnostics.push(PassDiagnostic {
                        severity: DiagnosticSeverity::Info,
                        code: "ALIAS_MAPPED_TO_CANONICAL".to_string(),
                        message: format!(
                            "Entity {} preferred name '{}' matches canonical entity {}",
                            entity.id, entity.preferred_name, canonical_id
                        ),
                        entity_id: Some(entity.id),
                    });
                    changes_applied += 1;
                }
            }
        }

        PassReport::basic(
            self.name(),
            items_processed,
            changes_applied,
            diagnostics,
            start.elapsed(),
        )
    }
}

/// Duplicate detection pass that proposes merges with feature explanations without mutating identities inline.
#[derive(Debug, Clone, Default)]
pub struct DuplicateDetectionPass {
    /// Minimum match confidence threshold to generate a merge proposal.
    pub threshold: f32,
}

impl DuplicateDetectionPass {
    /// Creates a new `DuplicateDetectionPass` with a custom confidence threshold.
    pub fn new(threshold: f32) -> Self {
        Self { threshold }
    }
}

impl ReconciliationPass for DuplicateDetectionPass {
    fn name(&self) -> &'static str {
        "DuplicateDetectionPass"
    }

    fn execute(&self, entities: &mut Vec<CanonicalEntity>) -> PassReport {
        let start = Instant::now();
        let items_processed = entities.len();
        let mut merge_proposals = Vec::new();
        let mut diagnostics = Vec::new();

        for i in 0..entities.len() {
            for j in (i + 1)..entities.len() {
                let e1 = &entities[i];
                let e2 = &entities[j];

                if e1.id == e2.id {
                    continue;
                }

                let mut lexical_score = 0.0f32;
                if e1.preferred_name == e2.preferred_name {
                    lexical_score = 1.0;
                } else if e1.aliases.contains(&e2.preferred_name)
                    || e2.aliases.contains(&e1.preferred_name)
                {
                    lexical_score = 0.85;
                }

                if lexical_score >= self.threshold {
                    let mut feature_scores = HashMap::new();
                    feature_scores.insert("lexical_similarity".to_string(), lexical_score);

                    merge_proposals.push(MergeProposal {
                        source_entity_id: e2.id,
                        target_entity_id: e1.id,
                        confidence: lexical_score,
                        feature_scores,
                        rationale: format!(
                            "Duplicate candidate between '{}' and '{}'",
                            e1.preferred_name, e2.preferred_name
                        ),
                        supporting_observations: Vec::new(),
                    });

                    diagnostics.push(PassDiagnostic {
                        severity: DiagnosticSeverity::Info,
                        code: "DUPLICATE_PROPOSAL_GENERATED".to_string(),
                        message: format!(
                            "Proposed merging entity {} ('{}') into {} ('{}') [confidence={:.2}]",
                            e2.id, e2.preferred_name, e1.id, e1.preferred_name, lexical_score
                        ),
                        entity_id: Some(e2.id),
                    });
                }
            }
        }

        // Sort proposals deterministically by (confidence desc, source_id, target_id)
        merge_proposals.sort_by(|a, b| {
            b.confidence
                .partial_cmp(&a.confidence)
                .unwrap_or(std::cmp::Ordering::Equal)
                .then_with(|| a.source_entity_id.cmp(&b.source_entity_id))
                .then_with(|| a.target_entity_id.cmp(&b.target_entity_id))
        });

        PassReport {
            pass_name: self.name(),
            items_processed,
            changes_applied: 0, // Detection only, zero mutations applied
            diagnostics,
            merge_proposals,
            contradiction_records: Vec::new(),
            duration: start.elapsed(),
        }
    }
}

/// Contradiction detection pass identifying logical vs. temporal conflicts.
#[derive(Debug, Clone, Default)]
pub struct ContradictionDetectionPass;

impl ContradictionDetectionPass {
    /// Creates a new `ContradictionDetectionPass`.
    pub fn new() -> Self {
        Self
    }
}

impl ReconciliationPass for ContradictionDetectionPass {
    fn name(&self) -> &'static str {
        "ContradictionDetectionPass"
    }

    fn execute(&self, entities: &mut Vec<CanonicalEntity>) -> PassReport {
        let start = Instant::now();
        let items_processed = entities.len();
        let mut contradiction_records = Vec::new();
        let mut diagnostics = Vec::new();

        for i in 0..entities.len() {
            for j in (i + 1)..entities.len() {
                let e1 = &entities[i];
                let e2 = &entities[j];

                if e1.preferred_name == e2.preferred_name && e1.id != e2.id {
                    let (kind, rationale) = match (e1.state, e2.state) {
                        (KnowledgeState::Archived, KnowledgeState::Observed)
                        | (KnowledgeState::Observed, KnowledgeState::Archived) => (
                            ContradictionKind::Temporal,
                            format!("Temporal contradiction: '{}' exists in Archived and Observed states simultaneously", e1.preferred_name),
                        ),
                        _ => (
                            ContradictionKind::Logical,
                            format!("Logical contradiction: multiple distinct active entities share preferred_name '{}'", e1.preferred_name),
                        ),
                    };

                    contradiction_records.push(ContradictionRecord {
                        kind,
                        entity_a: e1.id,
                        entity_b: e2.id,
                        confidence: 0.9,
                        rationale,
                        timestamp_delta: 0,
                    });

                    diagnostics.push(PassDiagnostic {
                        severity: DiagnosticSeverity::Warning,
                        code: "CONTRADICTION_DETECTED".to_string(),
                        message: format!(
                            "Contradiction detected between entity {} and entity {}",
                            e1.id, e2.id
                        ),
                        entity_id: Some(e1.id),
                    });
                }
            }
        }

        PassReport {
            pass_name: self.name(),
            items_processed,
            changes_applied: 0,
            diagnostics,
            merge_proposals: Vec::new(),
            contradiction_records,
            duration: start.elapsed(),
        }
    }
}

/// Policy governing orphan entity evaluation.
pub trait OrphanPolicy: Send + Sync {
    /// Evaluates whether an entity is considered an orphan subject to policy demotion.
    fn should_demote_orphan(&self, entity: &CanonicalEntity) -> bool;
}

/// Default orphan policy evaluating entity state and reliability without deleting singletons.
#[derive(Debug, Clone)]
pub struct DefaultOrphanPolicy {
    /// Minimum source reliability threshold required to prevent demotion.
    pub min_reliability: f32,
}

impl Default for DefaultOrphanPolicy {
    fn default() -> Self {
        Self {
            min_reliability: 0.2,
        }
    }
}

impl OrphanPolicy for DefaultOrphanPolicy {
    fn should_demote_orphan(&self, entity: &CanonicalEntity) -> bool {
        // Only demote unreinforced Observed entities with zero aliases and very low reliability
        entity.state == KnowledgeState::Observed
            && entity.aliases.is_empty()
            && entity.evidence.source_reliability < self.min_reliability
    }
}

/// Policy-driven orphan detection pass.
pub struct OrphanDetectionPass {
    policy: Box<dyn OrphanPolicy>,
}

impl Default for OrphanDetectionPass {
    fn default() -> Self {
        Self::new()
    }
}

impl OrphanDetectionPass {
    /// Creates a new `OrphanDetectionPass` with default policy.
    pub fn new() -> Self {
        Self {
            policy: Box::new(DefaultOrphanPolicy::default()),
        }
    }

    /// Creates a new `OrphanDetectionPass` with a custom orphan policy.
    pub fn with_policy<P: OrphanPolicy + 'static>(policy: P) -> Self {
        Self {
            policy: Box::new(policy),
        }
    }
}

impl ReconciliationPass for OrphanDetectionPass {
    fn name(&self) -> &'static str {
        "OrphanDetectionPass"
    }

    fn execute(&self, entities: &mut Vec<CanonicalEntity>) -> PassReport {
        let start = Instant::now();
        let mut changes_applied = 0;
        let items_processed = entities.len();
        let mut diagnostics = Vec::new();

        for entity in entities.iter_mut() {
            if self.policy.should_demote_orphan(entity) {
                entity.state = KnowledgeState::Weak;
                changes_applied += 1;
                diagnostics.push(PassDiagnostic {
                    severity: DiagnosticSeverity::Info,
                    code: "ORPHAN_DEMOTED_TO_WEAK".to_string(),
                    message: format!("Orphan policy demoted entity {} state to Weak", entity.id),
                    entity_id: Some(entity.id),
                });
            }
        }

        PassReport::basic(
            self.name(),
            items_processed,
            changes_applied,
            diagnostics,
            start.elapsed(),
        )
    }
}

/// Pipeline coordinator executing reconciliation passes in sequence.
#[derive(Default)]
pub struct ReconciliationPipeline {
    passes: Vec<Box<dyn ReconciliationPass>>,
}

impl ReconciliationPipeline {
    /// Creates a new empty `ReconciliationPipeline`.
    pub fn new() -> Self {
        Self { passes: Vec::new() }
    }

    /// Adds a reconciliation pass to the pipeline.
    #[allow(clippy::should_implement_trait)]
    pub fn add<P: ReconciliationPass + 'static>(mut self, pass: P) -> Self {
        self.passes.push(Box::new(pass));
        self
    }

    /// Adds a reconciliation pass to the pipeline.
    pub fn with_pass<P: ReconciliationPass + 'static>(self, pass: P) -> Self {
        self.add(pass)
    }

    /// Executes all configured passes sequentially and returns their execution reports.
    pub fn execute(&self, entities: &mut Vec<CanonicalEntity>) -> Vec<PassReport> {
        self.passes
            .iter()
            .map(|pass| pass.execute(entities))
            .collect()
    }
}
