[package]
name = "brain-plugins"
version = "0.1.0"
edition = "2021"

[dependencies]
brain-core = { path = "../brain-core" }
brain-domain = { path = "../brain-domain" }
semver = { version = "1.0", features = ["serde"] }
parking_lot = "0.12"
toml.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
