//! Value objects and types associated with the Job aggregate.

use crate::identifiers::SessionId;
use serde::{Deserialize, Serialize};
use std::num::NonZeroU64;

/// Strongly-typed identifier for background jobs.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct JobId(pub uuid::Uuid);

/// Categorical kind of background task execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobKind {
    /// External tool execution.
    Tool,
    /// Memory retrieval query execution.
    Retrieval,
    /// Codebase or repository semantic indexing task.
    Indexing,
    /// Synchronization or import operation.
    Sync,
    /// Compilation or building tasks.
    Compilation,
    /// Automated system/maintenance task.
    Maintenance,
}

/// Precedence priority tier for scheduling.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobPriority {
    /// High-priority blocker.
    Critical,
    /// Time-sensitive task.
    High,
    /// Normal background task.
    Normal,
    /// Low precedence/idle task.
    Low,
}

/// Scope context owner that requested the job.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "type")]
pub enum JobOwner {
    /// Initiated automatically by the core system daemon.
    System,
    /// Initiated explicitly by a user query.
    User {
        /// User identity handle.
        username: String,
    },
    /// Initiated within the context of an active session conversation.
    Session {
        /// Associated session ID.
        session_id: SessionId,
    },
}

/// Short human-readable task summary text.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct JobDescription(pub String);

/// Time representation value object.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct JobTimestamp(pub u64);

/// Structured error reason describing failure.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct JobFailureReason(pub String);

/// Execution capabilities associated with the job's kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobCapability {
    /// Job execution can be safely cancelled/aborted.
    Cancelable,
    /// Job produces output artifacts.
    ProducesArtifacts,
    /// Job writes logs.
    ProducesLogs,
    /// Job state persists across daemon restarts.
    Persistent,
}

/// Unit measure for tracking step completion.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ProgressUnit {
    /// Count of steps.
    Steps,
    /// Size of bytes.
    Bytes,
    /// Count of files.
    Files,
    /// Count of arbitrary items.
    Items,
}

/// Granular job execution progress value object.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum JobProgress {
    /// Execution status is ongoing but has no absolute total bound.
    Indeterminate,
    /// Execution progress tracking complete and total quantities.
    Determinate {
        /// Number of units completed.
        completed: u64,
        /// Total number of units expected.
        total: u64,
        /// The metric unit.
        unit: ProgressUnit,
    },
}

/// Strongly-typed identifier for job artifacts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct ArtifactId(pub uuid::Uuid);

/// Structured kind categories for job artifacts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactKind {
    /// Structured JSON payload.
    Json,
    /// Codebase patch/diff.
    Diff,
    /// Document formatted as Markdown.
    Markdown,
    /// Page formatted as HTML.
    Html,
    /// Plain text string.
    Text,
    /// Arbitrary binary file format.
    Binary,
    /// Custom extension category.
    Other,
}

/// Immutable output entry generated by job executor execution.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Artifact {
    /// Unique identifier for this artifact.
    pub id: ArtifactId,
    /// Structured classification.
    pub kind: ArtifactKind,
    /// The actual raw bytes payload.
    pub payload: Vec<u8>,
}

impl Artifact {
    /// Creates a new `Artifact` instance.
    pub fn new(id: ArtifactId, kind: ArtifactKind, payload: Vec<u8>) -> Self {
        Self { id, kind, payload }
    }
}

/// Chronological monotonic log sequence index.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct LogEntryId(pub NonZeroU64);

/// Diagnostic log line emitted during task execution.
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LogEntry {
    /// Monotonic log identifier.
    pub id: LogEntryId,
    /// Date when the log entry was emitted.
    pub timestamp: JobTimestamp,
    /// Log line text.
    pub message: String,
}

impl LogEntry {
    /// Creates a new `LogEntry` instance.
    pub fn new(id: LogEntryId, timestamp: JobTimestamp, message: String) -> Self {
        Self {
            id,
            timestamp,
            message,
        }
    }
}
