//! Reflection scheduler, planner, and executor enforcing 3-layer orchestration.

use crate::reflection::contracts::{ReflectionExecutionMode, ReflectionReport, ReflectionTask};
use brain_domain::CanonicalEntity;
use std::time::Instant;

/// Immutable execution plan generated by the ModularReflectionPlanner.
pub struct ReflectionPlan {
    /// Execution mode used to generate the plan.
    pub mode: ReflectionExecutionMode,
    /// Ordered sequence of tasks to execute.
    pub tasks: Vec<Box<dyn ReflectionTask>>,
}

impl ReflectionPlan {
    /// Creates a new `ReflectionPlan`.
    pub fn new(mode: ReflectionExecutionMode) -> Self {
        Self {
            mode,
            tasks: Vec::new(),
        }
    }

    /// Appends a task to the execution plan sequence.
    pub fn add_task<T: ReflectionTask + 'static>(&mut self, task: T) {
        self.tasks.push(Box::new(task));
    }
}

/// Planner responsible for deciding **what** tasks to execute for a given mode.
#[derive(Default)]
pub struct ModularReflectionPlanner {
    registered_tasks: Vec<Box<dyn ReflectionTask>>,
}

impl ModularReflectionPlanner {
    /// Creates a new empty `ModularReflectionPlanner`.
    pub fn new() -> Self {
        Self {
            registered_tasks: Vec::new(),
        }
    }

    /// Registers an available reflection task with the planner.
    pub fn register_task<T: ReflectionTask + 'static>(&mut self, task: T) {
        self.registered_tasks.push(Box::new(task));
    }

    /// Constructs an immutable `ReflectionPlan` for the specified execution mode.
    pub fn plan(&self, mode: ReflectionExecutionMode) -> ReflectionPlan {
        let mut plan = ReflectionPlan::new(mode);
        match mode {
            ReflectionExecutionMode::Dream => {
                // Predefined Dream Plan sequence: Repair -> Strengthen -> EmbeddingRefresh -> Centrality -> Summarize -> Optimize
                for task in &self.registered_tasks {
                    plan.tasks.push(task.clone_box());
                }
            }
            _ => {
                for task in &self.registered_tasks {
                    plan.tasks.push(task.clone_box());
                }
            }
        }
        plan
    }
}

/// Scheduler responsible for deciding **when** reflection runs.
#[derive(Default)]
pub struct ModularReflectionScheduler {
    planner: ModularReflectionPlanner,
}

impl ModularReflectionScheduler {
    /// Creates a new `ModularReflectionScheduler` wrapping a planner.
    pub fn new(planner: ModularReflectionPlanner) -> Self {
        Self { planner }
    }

    /// Triggers plan generation for the given execution mode.
    pub fn trigger(&self, mode: ReflectionExecutionMode) -> ReflectionPlan {
        self.planner.plan(mode)
    }
}

/// Executor responsible for executing a `ReflectionPlan` and producing a `ReflectionReport`.
#[derive(Default)]
pub struct ModularReflectionExecutor;

impl ModularReflectionExecutor {
    /// Creates a new `ModularReflectionExecutor`.
    pub fn new() -> Self {
        Self
    }

    /// Executes a `ReflectionPlan` on canonical entities, producing a unified `ReflectionReport`.
    pub fn execute_plan(
        &self,
        plan: &ReflectionPlan,
        entities: &mut Vec<CanonicalEntity>,
    ) -> ReflectionReport {
        let start = Instant::now();
        let mut task_reports = Vec::with_capacity(plan.tasks.len());
        let mut total_changes = 0;

        for task in &plan.tasks {
            let report = task.execute(entities);
            total_changes += report.changes_applied;
            task_reports.push(report);
        }

        ReflectionReport {
            execution_mode: plan.mode,
            task_reports,
            total_duration: start.elapsed(),
            total_changes,
        }
    }
}
